# Generated by Django 4.2.6 on 2023-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Tarif İsmi')),
                ('aciklama', models.TextField(max_length=250, verbose_name='Tarif Açıklması')),
                ('resim', models.FileField(blank=True, null=True, upload_to='tarifler/', verbose_name='Tarif Resmi')),
            ],
        ),
    ]
