# Generated by Django 4.2.6 on 2023-12-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, verbose_name='Blog Başlığı')),
                ('aciklama', models.TextField(max_length=250, verbose_name='Blog Açıklaması')),
                ('resim', models.FileField(blank=True, null=True, upload_to='bloglar', verbose_name='Blog Resmi')),
                ('tarih', models.DateField(auto_now_add=True)),
                ('saat', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
