# Generated by Django 4.2.6 on 2023-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0003_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.FileField(blank=True, null=True, upload_to='instagram/', verbose_name='Instagram Gönderi')),
            ],
        ),
        migrations.AlterField(
            model_name='urunler',
            name='fiyat',
            field=models.FloatField(verbose_name='Ürün Fiyatı'),
        ),
    ]
