# Generated by Django 4.2.6 on 2023-12-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0004_instagram_alter_urunler_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifler',
            name='aciklama',
            field=models.TextField(max_length=750, verbose_name='Tarif Açıklması'),
        ),
    ]
