# Generated by Django 4.2.6 on 2023-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0005_alter_tarifler_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglar',
            name='aciklama',
            field=models.TextField(max_length=750, verbose_name='Blog Açıklaması'),
        ),
    ]
