# Generated by Django 4.2.6 on 2023-12-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0008_kategori_urunler_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglar',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
