# Generated by Django 4.2.6 on 2023-12-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0010_alter_bloglar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
