# Generated by Django 4.2.6 on 2023-12-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0012_alter_urunler_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urunler',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
