# Generated by Django 4.2.6 on 2023-12-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0014_kategori_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='slug',
            new_name='slugKategori',
        ),
    ]
