# Generated by Django 4.2.6 on 2023-12-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0015_rename_slug_kategori_slugkategori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='slugKategori',
            new_name='slug',
        ),
    ]
