# Generated by Django 4.2.6 on 2023-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonapp', '0016_rename_slugkategori_kategori_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='urun1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ürün Giriniz'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='urun2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ürün Giriniz'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='urun3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ürün Giriniz'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='urun4',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ürün Giriniz'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='urun5',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ürün Giriniz'),
        ),
    ]
